// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package apb_gpr_pkg;

    localparam APB_GPR_DATA_WIDTH = 32;
    localparam APB_GPR_MIN_ADDR_WIDTH = 8;

    typedef struct {
        logic next;
    } apb_gpr__cfg_reg__strap_pin__in_t;

    typedef struct {
        apb_gpr__cfg_reg__strap_pin__in_t strap_pin;
    } apb_gpr__cfg_reg__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_02526367_name_33733a7a__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_02526367_name_33733a7a__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_02526367_name_33733a7a__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__in_t;

    typedef struct {
        logic [1:0] next;
    } apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__id_locked__in_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__id_locked__in_t id_locked;
    } apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__in_t;

    typedef struct {
        apb_gpr__cfg_reg__in_t cfg;
        apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__in_t m1_id1;
        apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__in_t m1_id2;
        apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__in_t m2_id1;
        apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__in_t m2_id2;
        apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__in_t m3_id1;
        apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__in_t m3_id2;
        apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__in_t m4_id1;
        apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__in_t m4_id2;
        apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__in_t m5_id1;
        apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__in_t m5_id2;
        apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__in_t m6_id1;
        apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__in_t m6_id2;
        apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__in_t m7_id1;
        apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__in_t m7_id2;
        apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__in_t m8_id1;
        apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__in_t m8_id2;
        apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__in_t m9_id1;
        apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__in_t m9_id2;
        apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__in_t m10_id1;
        apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__in_t m10_id2;
        apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__in_t m11_id1;
        apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__in_t m11_id2;
        apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__in_t m12_id1;
        apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__in_t m12_id2;
        apb_gpr__mutex_reg_desc_02526367_name_33733a7a__in_t m13_id1;
        apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__in_t m13_id2;
        apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__in_t m14_id1;
        apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__in_t m14_id2;
        apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__in_t m15_id1;
        apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__in_t m15_id2;
        apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__in_t m16_id1;
        apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__in_t m16_id2;
    } apb_gpr__in_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_sel_reg__pll_clk_sel_reg__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__clk_sel_reg__sdram_clk_sel_reg__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_sel_reg__apb_clk_sel_reg__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__clk_sel_reg__axi_apb_clk_sel_reg__out_t;

    typedef struct {
        apb_gpr__clk_sel_reg__pll_clk_sel_reg__out_t pll_clk_sel_reg;
        apb_gpr__clk_sel_reg__sdram_clk_sel_reg__out_t sdram_clk_sel_reg;
        apb_gpr__clk_sel_reg__apb_clk_sel_reg__out_t apb_clk_sel_reg;
        apb_gpr__clk_sel_reg__axi_apb_clk_sel_reg__out_t axi_apb_clk_sel_reg;
    } apb_gpr__clk_sel_reg__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_dma__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_scr1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_cva6__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_gpt__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_uart_0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_uart_1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_uart_l0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_uart_l1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_spi_l0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_spi_l1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_ps2_0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_ps2_1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_i2c__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_i2s__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_ethernet__out_t;

    typedef struct {
        logic value;
    } apb_gpr__soft_rst_reg__soft_rst_vga__out_t;

    typedef struct {
        apb_gpr__soft_rst_reg__soft_rst_dma__out_t soft_rst_dma;
        apb_gpr__soft_rst_reg__soft_rst_scr1__out_t soft_rst_scr1;
        apb_gpr__soft_rst_reg__soft_rst_cva6__out_t soft_rst_cva6;
        apb_gpr__soft_rst_reg__soft_rst_gpt__out_t soft_rst_gpt;
        apb_gpr__soft_rst_reg__soft_rst_uart_0__out_t soft_rst_uart_0;
        apb_gpr__soft_rst_reg__soft_rst_uart_1__out_t soft_rst_uart_1;
        apb_gpr__soft_rst_reg__soft_rst_uart_l0__out_t soft_rst_uart_l0;
        apb_gpr__soft_rst_reg__soft_rst_uart_l1__out_t soft_rst_uart_l1;
        apb_gpr__soft_rst_reg__soft_rst_spi_l0__out_t soft_rst_spi_l0;
        apb_gpr__soft_rst_reg__soft_rst_spi_l1__out_t soft_rst_spi_l1;
        apb_gpr__soft_rst_reg__soft_rst_ps2_0__out_t soft_rst_ps2_0;
        apb_gpr__soft_rst_reg__soft_rst_ps2_1__out_t soft_rst_ps2_1;
        apb_gpr__soft_rst_reg__soft_rst_i2c__out_t soft_rst_i2c;
        apb_gpr__soft_rst_reg__soft_rst_i2s__out_t soft_rst_i2s;
        apb_gpr__soft_rst_reg__soft_rst_ethernet__out_t soft_rst_ethernet;
        apb_gpr__soft_rst_reg__soft_rst_vga__out_t soft_rst_vga;
    } apb_gpr__soft_rst_reg__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_scr1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_dma__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_cva6__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_gpt__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_uart_0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_uart_1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_uart_l0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_uart_l1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_spi_l0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_spi_l1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_ps2_0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_ps2_1__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_i2c__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_i2s__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_ethernet__out_t;

    typedef struct {
        logic value;
    } apb_gpr__clk_gating_reg__clk_gating_vga__out_t;

    typedef struct {
        apb_gpr__clk_gating_reg__clk_gating_scr1__out_t clk_gating_scr1;
        apb_gpr__clk_gating_reg__clk_gating_dma__out_t clk_gating_dma;
        apb_gpr__clk_gating_reg__clk_gating_cva6__out_t clk_gating_cva6;
        apb_gpr__clk_gating_reg__clk_gating_gpt__out_t clk_gating_gpt;
        apb_gpr__clk_gating_reg__clk_gating_uart_0__out_t clk_gating_uart_0;
        apb_gpr__clk_gating_reg__clk_gating_uart_1__out_t clk_gating_uart_1;
        apb_gpr__clk_gating_reg__clk_gating_uart_l0__out_t clk_gating_uart_l0;
        apb_gpr__clk_gating_reg__clk_gating_uart_l1__out_t clk_gating_uart_l1;
        apb_gpr__clk_gating_reg__clk_gating_spi_l0__out_t clk_gating_spi_l0;
        apb_gpr__clk_gating_reg__clk_gating_spi_l1__out_t clk_gating_spi_l1;
        apb_gpr__clk_gating_reg__clk_gating_ps2_0__out_t clk_gating_ps2_0;
        apb_gpr__clk_gating_reg__clk_gating_ps2_1__out_t clk_gating_ps2_1;
        apb_gpr__clk_gating_reg__clk_gating_i2c__out_t clk_gating_i2c;
        apb_gpr__clk_gating_reg__clk_gating_i2s__out_t clk_gating_i2s;
        apb_gpr__clk_gating_reg__clk_gating_ethernet__out_t clk_gating_ethernet;
        apb_gpr__clk_gating_reg__clk_gating_vga__out_t clk_gating_vga;
    } apb_gpr__clk_gating_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } apb_gpr__gpr_reg_desc_159dc8d2_name_159dc8d2__value__out_t;

    typedef struct {
        apb_gpr__gpr_reg_desc_159dc8d2_name_159dc8d2__value__out_t value;
    } apb_gpr__gpr_reg_desc_159dc8d2_name_159dc8d2__out_t;

    typedef struct {
        logic [31:0] value;
    } apb_gpr__gpr_reg_desc_3b97b422_name_3b97b422__value__out_t;

    typedef struct {
        apb_gpr__gpr_reg_desc_3b97b422_name_3b97b422__value__out_t value;
    } apb_gpr__gpr_reg_desc_3b97b422_name_3b97b422__out_t;

    typedef struct {
        logic [31:0] value;
    } apb_gpr__gpr_reg_desc_80933ce0_name_80933ce0__value__out_t;

    typedef struct {
        apb_gpr__gpr_reg_desc_80933ce0_name_80933ce0__value__out_t value;
    } apb_gpr__gpr_reg_desc_80933ce0_name_80933ce0__out_t;

    typedef struct {
        logic value;
    } apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__scr1_irq_hwclr_ebc057f2_hwset_f4e029dd__out_t;

    typedef struct {
        logic value;
    } apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__cva6_irq_hwclr_458801b8_hwset_9551e958__out_t;

    typedef struct {
        apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__scr1_irq_hwclr_ebc057f2_hwset_f4e029dd__out_t scr1_irq;
        apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__cva6_irq_hwclr_458801b8_hwset_9551e958__out_t cva6_irq;
    } apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__out_t;

    typedef struct {
        logic value;
    } apb_gpr__test_status_reg__started__out_t;

    typedef struct {
        logic value;
    } apb_gpr__test_status_reg__running__out_t;

    typedef struct {
        logic value;
    } apb_gpr__test_status_reg__status__out_t;

    typedef struct {
        apb_gpr__test_status_reg__started__out_t started;
        apb_gpr__test_status_reg__running__out_t running;
        apb_gpr__test_status_reg__status__out_t status;
    } apb_gpr__test_status_reg__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_02526367_name_33733a7a__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_02526367_name_33733a7a__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_02526367_name_33733a7a__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__out_t;

    typedef struct {
        logic [1:0] value;
    } apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__id_locked__out_t;

    typedef struct {
        apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__id_locked__out_t id_locked;
    } apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__out_t;

    typedef struct {
        apb_gpr__clk_sel_reg__out_t clk_sel;
        apb_gpr__soft_rst_reg__out_t soft_rst;
        apb_gpr__clk_gating_reg__out_t clk_gating;
        apb_gpr__gpr_reg_desc_159dc8d2_name_159dc8d2__out_t boot_addr;
        apb_gpr__gpr_reg_desc_3b97b422_name_3b97b422__out_t scr1_irq_desc;
        apb_gpr__gpr_reg_desc_80933ce0_name_80933ce0__out_t cva6_irq_desc;
        apb_gpr__core_irq_reg_cva6_irq_1b92062b_scr1_irq_7f48a61e__out_t core_irq_flag;
        apb_gpr__test_status_reg__out_t test_status;
        apb_gpr__mutex_reg_desc_90a102c2_name_ceb1ad6d__out_t m1_id1;
        apb_gpr__mutex_reg_desc_754c83dd_name_206e1237__out_t m1_id2;
        apb_gpr__mutex_reg_desc_870c5965_name_dfd587c1__out_t m2_id1;
        apb_gpr__mutex_reg_desc_0296f3cf_name_6702da33__out_t m2_id2;
        apb_gpr__mutex_reg_desc_cedea36c_name_5d835252__out_t m3_id1;
        apb_gpr__mutex_reg_desc_8f3f291b_name_d4f5bcf1__out_t m3_id2;
        apb_gpr__mutex_reg_desc_aef664dc_name_efe614f2__out_t m4_id1;
        apb_gpr__mutex_reg_desc_1df45463_name_f61f0840__out_t m4_id2;
        apb_gpr__mutex_reg_desc_c7124ad8_name_97b18448__out_t m5_id1;
        apb_gpr__mutex_reg_desc_945f41a9_name_ca6d06db__out_t m5_id2;
        apb_gpr__mutex_reg_desc_e37b1873_name_0f2dc893__out_t m6_id1;
        apb_gpr__mutex_reg_desc_97c74951_name_c0682a09__out_t m6_id2;
        apb_gpr__mutex_reg_desc_3a6092a7_name_995176ce__out_t m7_id1;
        apb_gpr__mutex_reg_desc_82e1ebe8_name_17272832__out_t m7_id2;
        apb_gpr__mutex_reg_desc_85388d24_name_dca1e22c__out_t m8_id1;
        apb_gpr__mutex_reg_desc_54a3360c_name_d788c32b__out_t m8_id2;
        apb_gpr__mutex_reg_desc_f3f127da_name_2cb0d71b__out_t m9_id1;
        apb_gpr__mutex_reg_desc_42120e80_name_20bbb295__out_t m9_id2;
        apb_gpr__mutex_reg_desc_53c67d34_name_dd860726__out_t m10_id1;
        apb_gpr__mutex_reg_desc_9e5e4c5a_name_6455f79f__out_t m10_id2;
        apb_gpr__mutex_reg_desc_a51d0bc0_name_22062c59__out_t m11_id1;
        apb_gpr__mutex_reg_desc_b596eb03_name_bcafb150__out_t m11_id2;
        apb_gpr__mutex_reg_desc_006b6782_name_6bccbee9__out_t m12_id1;
        apb_gpr__mutex_reg_desc_a0454b91_name_44c0dc3e__out_t m12_id2;
        apb_gpr__mutex_reg_desc_02526367_name_33733a7a__out_t m13_id1;
        apb_gpr__mutex_reg_desc_4832bd47_name_fc79b651__out_t m13_id2;
        apb_gpr__mutex_reg_desc_f8cbfbad_name_604e05dd__out_t m14_id1;
        apb_gpr__mutex_reg_desc_cc48a8a1_name_5b35b8b9__out_t m14_id2;
        apb_gpr__mutex_reg_desc_d958c657_name_bea8abf2__out_t m15_id1;
        apb_gpr__mutex_reg_desc_1f2b7abf_name_727e8de4__out_t m15_id2;
        apb_gpr__mutex_reg_desc_fee57218_name_471b3f3e__out_t m16_id1;
        apb_gpr__mutex_reg_desc_37e864db_name_08af73d4__out_t m16_id2;
    } apb_gpr__out_t;
endpackage
